export const events = [
    {
        image: '/images/event1.png',
        title: 'Spring Equinox Music Festival',
        slug: 'spring-equinox-festival',
        location: 'Main Campus Quad',
        date: 'March 21, 2026',
        time: '4:00 PM',
    },
    {
        image: '/images/event2.png',
        title: 'Retro Gaming Night',
        slug: 'retro-gaming-night',
        location: 'Student Union Basement',
        date: 'March 25, 2026',
        time: '7:00 PM',
    },
    {
        image: '/images/event3.png',
        title: 'Midnight Breakfast Social',
        slug: 'midnight-breakfast-social',
        location: 'Dining Hall A',
        date: 'April 2, 2026',
        time: '11:30 PM',
    },
    {
        image: '/images/event4.png',
        title: 'Tech & Startup Career Mixer',
        slug: 'tech-startup-mixer',
        location: 'Innovation Hub',
        date: 'April 10, 2026',
        time: '2:00 PM',
    },
    {
        image: '/images/event5.png',
        title: 'Annual Arts Showcase',
        slug: 'annual-arts-showcase',
        location: 'Fine Arts Gallery',
        date: 'April 15, 2026',
        time: '6:00 PM',
    },
    {
        image: '/images/event6.png',
        title: 'Outdoor Movie Night: Sci-Fi Marathon',
        slug: 'outdoor-movie-night',
        location: 'West Lawn',
        date: 'April 22, 2026',
        time: '8:30 PM',
    },
];